version: "3.8"

services:
  miniflux:
    build: miniflux
    restart: "no"
    environment:
      - DB_HOST=db:5432
      - DATABASE_URL=postgres://postgres:postgres@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13.1
    restart: "no"
    environment:
      - POSTGRES_DB=miniflux
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: