version: "3.8"

services:
  miniflux:
    build: miniflux
    restart: "no"
    environment:
      - DB_HOST=miniflux-db:5432
      - DATABASE_URL=postgres://miniflux:password@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - miniflux-db

  miniflux-db:
    image: postgres:13.6
    restart: "no"
    environment:
      - POSTGRES_DB=miniflux
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=password
    volumes:
      - miniflux_db:/var/lib/postgresql/data

volumes:
  miniflux_db:
