version: "3.8"

services:
  miniflux:
    build: miniflux
    restart: always
    environment:
      - DB_HOST=miniflux-db:5432
      - BASE_URL
      - DATABASE_URL
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - POLLING_FREQUENCY=60
      - POLLING_PARSING_ERROR_LIMIT=0
      - BATCH_SIZE=100
      - POLLING_SCHEDULER=entry_frequency
      - SCHEDULER_ENTRY_FREQUENCY_MAX_INTERVAL=1440
      - SCHEDULER_ENTRY_FREQUENCY_MIN_INTERVAL=5
      - CLEANUP_ARCHIVE_UNREAD_DAYS=-1
      - VIRTUAL_HOST
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      - default
      - proxy
    depends_on:
      - miniflux-db

  miniflux-db:
    image: postgres:13.6
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - miniflux_db:/var/lib/postgresql/data
    networks:
      - default

volumes:
  miniflux_db:

networks:
  proxy:
    name: nginx-proxy
    external: true
