version: "3.8"

services:
  miniflux:
    build: miniflux
    restart: always
    environment:
      - DB_HOST=db:5432
      - DATABASE_URL
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - VIRTUAL_HOST
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    depends_on:
      - db

  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  default:
    external:
      name: nginx-proxy
